### ISSUE TITLE
example.js fails with kyuubi

### ISSUE THREAD

**Issue by SimSt7** [lenchv/hive-driver#51]
I am using a PlainTcpConnection to Apache Kyuubi 1.6.0 and try to run example.js.  Table creation and insertion works, but table selection fails with below error log. Reproduced it with v.0.1.7 and pre-release 0.2.0.

TypeError: Cannot read properties of undefined (reading 'binaryVal')
    at JsonResult.getColumnValue (/home/user/Desktop/hive-test/hive-driver/dist/result/JsonResult.js:123:22)
    at JsonResult.getSchemaValues (/home/user/Desktop/hive-test/hive-driver/dist/result/JsonResult.js:56:32)
    at /home/user/Desktop/hive-test/hive-driver/dist/result/JsonResult.js:42:26
    at Array.reduce (<anonymous>)
    at JsonResult.getRows (/home/user/Desktop/hive-test/hive-driver/dist/result/JsonResult.js:41:28)
    at /home/user/Desktop/hive-test/hive-driver/dist/result/JsonResult.js:29:30
    at Array.reduce (<anonymous>)
    at JsonResult.getValue (/home/user/Desktop/hive-test/hive-driver/dist/result/JsonResult.js:27:26)
    at /home/user/Desktop/hive-test/hive-driver/examples/example.js:45:57
    at processTicksAndRejections (node:internal/process/task_queues:96:5) #

**Comment by lenchv** [comment]
Hi @SimSt7, I haven't reproduced it, but it might relate to these changes
https://github.com/lenchv/hive-driver/commit/3c674de7bac9ccd4b3d1bc2f5cd14deb9bdb1055

anyway, I made it bulletproof, if you have a chance please check and let me know whether it fixed your issue
